# Generated by Django 3.2.1 on 2022-02-17 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportalFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='file/')),
            ],
        ),
        migrations.CreateModel(
            name='ExportalFileLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='file/')),
            ],
        ),
        migrations.CreateModel(
            name='InternalFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='file/')),
            ],
        ),
        migrations.CreateModel(
            name='InternalFileLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='file/')),
            ],
        ),
        migrations.CreateModel(
            name='linedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='file/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stone_name', models.CharField(max_length=125)),
                ('created', models.DateField()),
                ('working_breast_code', models.CharField(max_length=125)),
                ('serial_number_of_the_peak_in_the_mine', models.CharField(max_length=125)),
                ('add', models.DateField(auto_now_add=True)),
                ('approximate_tonnage', models.PositiveIntegerField()),
                ('unique_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_special', models.BooleanField(default=False)),
                ('length', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('stair_code', models.CharField(max_length=10)),
                ('buyer', models.CharField(blank=True, max_length=255, null=True)),
                ('grading_code', models.CharField(max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('rejected', models.BooleanField(default=True)),
                ('loaded', models.BooleanField(default=True)),
                ('mine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.mine')),
            ],
        ),
        migrations.CreateModel(
            name='ExportalProduct',
            fields=[
                ('productbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.productbase')),
                ('color_code', models.CharField(max_length=10)),
                ('code_Slate', models.CharField(max_length=10)),
            ],
            bases=('product.productbase',),
        ),
        migrations.CreateModel(
            name='InternalProduct',
            fields=[
                ('productbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.productbase')),
            ],
            bases=('product.productbase',),
        ),
        migrations.CreateModel(
            name='LinedProduct',
            fields=[
                ('productbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.productbase')),
            ],
            bases=('product.productbase',),
        ),
        migrations.CreateModel(
            name='Rejected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_date', models.DateField()),
                ('created', models.DateField(auto_now_add=True)),
                ('freight_number', models.CharField(max_length=125)),
                ('weight_of_scales', models.PositiveIntegerField()),
                ('buyer', models.CharField(max_length=255)),
                ('serial_number_of_the_peak_in_the_mine', models.CharField(max_length=125)),
                ('mine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.mine')),
            ],
        ),
        migrations.CreateModel(
            name='Loaded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_date', models.DateField()),
                ('created', models.DateField(auto_now_add=True)),
                ('freight_number', models.CharField(max_length=125)),
                ('weight_of_scales', models.PositiveIntegerField()),
                ('buyer', models.CharField(max_length=255)),
                ('serial_number_of_the_peak_in_the_mine', models.CharField(max_length=125)),
                ('mine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.mine')),
            ],
        ),
        migrations.CreateModel(
            name='InternalLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_internal_logo', to='product.internalproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Internal_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='image/product/')),
                ('product_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='product.internalproduct')),
            ],
        ),
        migrations.CreateModel(
            name='ImageLinedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_lined', to='product.linedproduct')),
            ],
        ),
        migrations.CreateModel(
            name='ImageInternalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_internal', to='product.internalproduct')),
            ],
        ),
        migrations.CreateModel(
            name='ImageExportalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_exportal', to='product.exportalproduct')),
            ],
        ),
        migrations.CreateModel(
            name='ExportalLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_exportal_logo', to='product.exportalproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Exportal_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='image/product/')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='product.exportalproduct')),
            ],
        ),
    ]
