# Generated by Django 3.2.1 on 2022-02-19 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageExportalModel',
            new_name='ExportalGalleries',
        ),
        migrations.RenameModel(
            old_name='InternalFile',
            new_name='ExportalGalleriesFile',
        ),
        migrations.RenameModel(
            old_name='ExportalLogo',
            new_name='ExportalMainPic',
        ),
        migrations.RenameModel(
            old_name='ExportalFileLogo',
            new_name='ExportalMainPicFile',
        ),
        migrations.RenameModel(
            old_name='ImageInternalModel',
            new_name='InternalGalleries',
        ),
        migrations.RenameModel(
            old_name='linedFile',
            new_name='InternalGalleriesFile',
        ),
        migrations.RenameModel(
            old_name='InternalLogo',
            new_name='InternalMainPic',
        ),
        migrations.RenameModel(
            old_name='InternalFileLogo',
            new_name='InternalMainPicFile',
        ),
        migrations.DeleteModel(
            name='ExportalFile',
        ),
        migrations.RemoveField(
            model_name='internal_image',
            name='product_name',
        ),
        migrations.DeleteModel(
            name='ImageLinedModel',
        ),
        migrations.DeleteModel(
            name='Internal_Image',
        ),
    ]
