# Generated by Django 3.2.1 on 2022-02-19 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20220219_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinedProductMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approximate_tonnage', models.PositiveIntegerField()),
                ('unique_id', models.CharField(max_length=64)),
                ('lined_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.linedproduct')),
            ],
        ),
    ]
