# Generated by Django 3.2.1 on 2022-02-19 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('product', '0003_linedproductmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='productbase',
            name='loaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productbase',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='linedproductmember',
            name='lined_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.linedproducts'),
        ),
        migrations.DeleteModel(
            name='LinedProduct',
        ),
    ]
