# Generated by Django 3.2.1 on 2022-02-19 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_linedproducts_line_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exportal_Image',
        ),
    ]
