# Generated by Django 3.2.1 on 2022-02-17 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0002_auto_20220217_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='pin',
        ),
    ]
