# Generated by Django 3.2.1 on 2022-02-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0003_remove_visit_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hold',
            name='field',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='field',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='field',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
