# Generated by Django 3.2.1 on 2022-02-17 21:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0004_auto_20220218_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='hold',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sample',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='visit',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
